# Generated by Django 5.1.2 on 2024-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(help_text='Select a cover for this book', null=True, upload_to='images/'),
        ),
    ]
